/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ekran;

import Nesneler.Masa;
import Nesneler.Rezervasyon;
import Nesneler.VeriTabani;
import static ekran.KullaniciEkran.comboboxModel;
import java.sql.Connection;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cruz
 */
public class RezervasyonEkranim extends javax.swing.JFrame {

 static ArrayList<Masa> masalar = null;
 static Connection baglanti = null;
 static Statement stmt = null;
 private int masaNo;
 private String saat;
 private String tarih;
 static ComboBoxModel comboboxModel;

 public RezervasyonEkranim() {
  initComponents();
  zamaniOlustur();
  tarihOlustur();
  comboboxModel = new DefaultComboBoxModel();
  masaDoldur();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  comboboxRezervasyon = new javax.swing.JComboBox();
  jButton1 = new javax.swing.JButton();
  saatCombo = new javax.swing.JComboBox<String>();
  dakikaCombo = new javax.swing.JComboBox<String>();
  gunCombo = new javax.swing.JComboBox<String>();
  ayCombo = new javax.swing.JComboBox<String>();
  yilCombo = new javax.swing.JComboBox<String>();
  jLabel1 = new javax.swing.JLabel();
  jLabel2 = new javax.swing.JLabel();
  jLabel3 = new javax.swing.JLabel();
  jLabel4 = new javax.swing.JLabel();
  jLabel5 = new javax.swing.JLabel();
  jLabel6 = new javax.swing.JLabel();

  setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
  setTitle("Rezervasyon Sayfası");
  setResizable(false);

  comboboxRezervasyon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

  jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
  jButton1.setText("Rezerv Et");
  jButton1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    jButton1ActionPerformed(evt);
   }
  });

  dakikaCombo.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    dakikaComboActionPerformed(evt);
   }
  });

  jLabel1.setText(":");

  jLabel2.setText("/");

  jLabel3.setText("/");

  jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
  jLabel4.setText("Masa no :");

  jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
  jLabel5.setText("Saat      :");

  jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
  jLabel6.setText("Tarih      :");

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
  getContentPane().setLayout(layout);
  layout.setHorizontalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(22, 22, 22)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
     .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
     .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
     .addGroup(layout.createSequentialGroup()
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
       .addComponent(saatCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       .addComponent(comboboxRezervasyon, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
      .addComponent(jLabel1)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(dakikaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
     .addGroup(layout.createSequentialGroup()
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
       .addGroup(layout.createSequentialGroup()
        .addComponent(gunCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(ayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
       .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGap(18, 18, 18)
      .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
      .addComponent(yilCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );
  layout.setVerticalGroup(
   layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(layout.createSequentialGroup()
    .addGap(38, 38, 38)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(comboboxRezervasyon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addGap(3, 3, 3)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(saatCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(jLabel1)
     .addComponent(dakikaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(jLabel5))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
     .addComponent(jLabel2)
     .addComponent(gunCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(ayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(jLabel3)
     .addComponent(yilCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
     .addComponent(jLabel6))
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addContainerGap())
  );

  pack();
  setLocationRelativeTo(null);
 }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     masaNo = Integer.valueOf(comboboxRezervasyon.getSelectedItem().toString());
     saat = saatCombo.getSelectedItem().toString() + " : " + dakikaCombo.getSelectedItem().toString();
     tarih = gunCombo.getSelectedItem().toString() + " / " + ayCombo.getSelectedItem().toString() + " / " + yilCombo.getSelectedItem().toString();

     baglanti = VeriTabani.veritabaninaBaglan();
     rezervasyonOlustur(masaNo, saat, tarih, baglanti);
     int sonRezervasyonID = VeriTabani.sonRezervasyonCek(baglanti);
     VeriTabani.masaRezervasyonGuncelle(sonRezervasyonID, masaNo, baglanti);
     
     try {
      VeriTabani.baglantiKapat(baglanti);
     } catch (Exception ex) {
      Logger.getLogger(YemekOlusturEkran.class.getName()).log(Level.SEVERE, null, ex);
     }
     this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dakikaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dakikaComboActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_dakikaComboActionPerformed
 public static void rezervasyonOlustur(int masano, String rezerv_saat, String rezerv_tarih, Connection baglanti) {
  try {
   stmt = baglanti.createStatement();
   String sql = "INSERT INTO rezervasyon (tarihi,saat,masano) "
           + "VALUES ('" + rezerv_tarih + "','" + rezerv_saat + "', '" + masano + "');";
   stmt.executeUpdate(sql);
   stmt.close();
   baglanti.commit();
   JOptionPane.showMessageDialog(null, "Rezervasyon Başarıyla Oluşturuldu.", "Bilgilendirme", JOptionPane.INFORMATION_MESSAGE);
  } catch (Exception e) {
   JOptionPane.showMessageDialog(null, "Rezervasyon Oluşturulamadı", "Error", JOptionPane.ERROR_MESSAGE);
   e.printStackTrace();
  }

 }

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
   * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(RezervasyonEkranim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(RezervasyonEkranim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(RezervasyonEkranim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(RezervasyonEkranim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
        //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new RezervasyonEkranim().setVisible(true);

   }
  });
 }

 public static void zamaniOlustur() {
  for (int i = 0; i < 24; i++) {
   if (i < 10) {
    saatCombo.addItem(String.valueOf(0) + String.valueOf(i));
   } else {
    saatCombo.addItem(String.valueOf(i));
   }
  }

  for (int j = 0; j <= 59; j++) {
   if (j < 10) {
    dakikaCombo.addItem(String.valueOf(0) + String.valueOf(j));
   } else {
    dakikaCombo.addItem(String.valueOf(j));
   }
  }

 }

 public static void tarihOlustur() {
  for (int i = 1; i <= 31; i++) {
   if (i < 10) {
    gunCombo.addItem(String.valueOf(0) + String.valueOf(i));
   } else {
    gunCombo.addItem(String.valueOf(i));
   }
  }

  for (int j = 0; j <= 12; j++) {
   if (j < 10) {
    ayCombo.addItem(String.valueOf(0) + String.valueOf(j + 1));
   } else {
    ayCombo.addItem(String.valueOf(j));
   }
  }

  for (int k = 0; k < 3; k++) {
   yilCombo.addItem(String.valueOf(2015 + k));
  }

 }

 public static void masaDoldur() {
 Connection baglanti = null;
  baglanti = VeriTabani.veritabaninaBaglan();
  masalar = VeriTabani.masaCek();
  String[] masaDizisi = new String[masalar.size()];
  for (int i = 0; i < masalar.size(); i++) {
   masaDizisi[i] = (String.valueOf(masalar.get(i).getMasaNo()));
  }
  
  comboboxModel = new DefaultComboBoxModel(masaDizisi);
  comboboxRezervasyon.setModel(comboboxModel);
  try {
   VeriTabani.baglantiKapat(baglanti);
  } catch (Exception e) {
  }
 }

 
 // Variables declaration - do not modify//GEN-BEGIN:variables
 private static javax.swing.JComboBox<String> ayCombo;
 private static javax.swing.JComboBox comboboxRezervasyon;
 private static javax.swing.JComboBox<String> dakikaCombo;
 private static javax.swing.JComboBox<String> gunCombo;
 private javax.swing.JButton jButton1;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JLabel jLabel2;
 private javax.swing.JLabel jLabel3;
 private javax.swing.JLabel jLabel4;
 private javax.swing.JLabel jLabel5;
 private javax.swing.JLabel jLabel6;
 private static javax.swing.JComboBox<String> saatCombo;
 private static javax.swing.JComboBox<String> yilCombo;
 // End of variables declaration//GEN-END:variables
}
