
import ekran.KullaniciEkran;
import ekran.YoneticiEkran;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author Cruz
 */
public class AnaEkran extends javax.swing.JFrame {

 private String kAdi="ömer";
 private String kSifre="çelik";
 
 /**
  * Creates new form Kullanici
  */
 public AnaEkran() {
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jPanel1 = new javax.swing.JPanel();
  butonKullanici = new javax.swing.JButton();
  butonYonetici = new javax.swing.JButton();
  jPanel2 = new javax.swing.JPanel();
  textKullaniciAdi = new javax.swing.JTextField();
  PassTextSifre = new javax.swing.JPasswordField();
  butonYoneticiGiris = new javax.swing.JButton();
  jLabel1 = new javax.swing.JLabel();

  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  setTitle("Giriş Sayfası");
  setMaximumSize(new java.awt.Dimension(637, 469));
  setMinimumSize(new java.awt.Dimension(637, 469));
  setPreferredSize(new java.awt.Dimension(637, 469));
  setResizable(false);
  getContentPane().setLayout(null);

  jPanel1.setOpaque(false);

  butonKullanici.setBackground(new java.awt.Color(0, 0, 102));
  butonKullanici.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
  butonKullanici.setForeground(new java.awt.Color(255, 255, 255));
  butonKullanici.setText("Kullanıcı Girişi");
  butonKullanici.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    butonKullaniciActionPerformed(evt);
   }
  });

  butonYonetici.setBackground(new java.awt.Color(0, 0, 102));
  butonYonetici.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
  butonYonetici.setForeground(new java.awt.Color(255, 255, 255));
  butonYonetici.setText("Yönetici Girişi");
  butonYonetici.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    butonYoneticiActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
  jPanel1.setLayout(jPanel1Layout);
  jPanel1Layout.setHorizontalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
     .addComponent(butonKullanici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
     .addComponent(butonYonetici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );
  jPanel1Layout.setVerticalGroup(
   jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel1Layout.createSequentialGroup()
    .addContainerGap()
    .addComponent(butonKullanici)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(butonYonetici)
    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
  );

  getContentPane().add(jPanel1);
  jPanel1.setBounds(0, 0, 160, 90);

  jPanel2.setOpaque(false);

  textKullaniciAdi.setBackground(new java.awt.Color(0, 51, 153));
  textKullaniciAdi.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
  textKullaniciAdi.setForeground(new java.awt.Color(255, 255, 255));
  textKullaniciAdi.setText("ömer");

  PassTextSifre.setBackground(new java.awt.Color(0, 51, 153));
  PassTextSifre.setForeground(new java.awt.Color(255, 255, 255));
  PassTextSifre.setText("çelik");

  butonYoneticiGiris.setBackground(new java.awt.Color(0, 0, 102));
  butonYoneticiGiris.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
  butonYoneticiGiris.setForeground(new java.awt.Color(255, 255, 255));
  butonYoneticiGiris.setText("Yönetici Giriş");
  butonYoneticiGiris.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    butonYoneticiGirisActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
  jPanel2.setLayout(jPanel2Layout);
  jPanel2Layout.setHorizontalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addContainerGap()
    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
     .addGroup(jPanel2Layout.createSequentialGroup()
      .addGap(10, 10, 10)
      .addComponent(butonYoneticiGiris))
     .addComponent(PassTextSifre)
     .addComponent(textKullaniciAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
    .addContainerGap(29, Short.MAX_VALUE))
  );
  jPanel2Layout.setVerticalGroup(
   jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
   .addGroup(jPanel2Layout.createSequentialGroup()
    .addComponent(textKullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(PassTextSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
    .addComponent(butonYoneticiGiris)
    .addContainerGap(20, Short.MAX_VALUE))
  );

  getContentPane().add(jPanel2);
  jPanel2.setBounds(150, 10, 170, 120);

  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resimler/giris.jpg"))); // NOI18N
  getContentPane().add(jLabel1);
  jLabel1.setBounds(0, 0, 640, 470);

  pack();
  setLocationRelativeTo(null);
 }// </editor-fold>//GEN-END:initComponents

 private void butonKullaniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonKullaniciActionPerformed
  // TODO add your handling code here:
  
  KullaniciEkran kEkran=new KullaniciEkran();
  kEkran.show(); 
  YoneticiEkran yEkran=new YoneticiEkran();
  yEkran.show();
  this.dispose();
 }//GEN-LAST:event_butonKullaniciActionPerformed

 private void butonYoneticiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonYoneticiActionPerformed
  // TODO add your handling code here:
  jPanel2.setVisible(true);
 }//GEN-LAST:event_butonYoneticiActionPerformed

 private void butonYoneticiGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonYoneticiGirisActionPerformed
  // TODO add your handling code here:
  String kontrolKAdi=textKullaniciAdi.getText();
  String kontrolKSifre=PassTextSifre.getText();
  
  if(kAdi.equals(kontrolKAdi)&&kSifre.equals(kontrolKSifre)){
   YoneticiEkran yEkran =new YoneticiEkran();  
   yEkran.show();
    KullaniciEkran kEkran=new KullaniciEkran();
  kEkran.show(); 
   this.dispose();
  }
  else{
   JOptionPane.showMessageDialog(this, "Yanlış Cevap.");
  }
  
 }//GEN-LAST:event_butonYoneticiGirisActionPerformed

 /**
  * @param args the command line arguments
  */
 public static void main(String args[]) {
  /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
   * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
   */
  try {
   for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
    }
   }
  } catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (InstantiationException ex) {
   java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (IllegalAccessException ex) {
   java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
   java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
  }
        //</editor-fold>

  /* Create and display the form */
  java.awt.EventQueue.invokeLater(new Runnable() {
   public void run() {
    new AnaEkran().setVisible(true);
     jPanel2.setVisible(false);
   }
  });
  
 
 }

 
 
 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JPasswordField PassTextSifre;
 private javax.swing.JButton butonKullanici;
 private javax.swing.JButton butonYonetici;
 private javax.swing.JButton butonYoneticiGiris;
 private javax.swing.JLabel jLabel1;
 private javax.swing.JPanel jPanel1;
 private static javax.swing.JPanel jPanel2;
 private javax.swing.JTextField textKullaniciAdi;
 // End of variables declaration//GEN-END:variables
}
